export type PolicyContentBlock =
  | { type: "paragraph"; text: string }
  | { type: "subheading"; text: string }
  | { type: "list"; items: string[] };

export const privacyPolicyIntro =
  "At Accura (accura.one, “we”, “our”, “us”), we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your personal information in accordance with the Australian Privacy Principles (APPs) contained in the Privacy Act 1988 (Cth).";

export const privacyPolicySections: Array<{
  title: string;
  blocks: PolicyContentBlock[];
}> = [
  {
    title: "1. Information We Collect",
    blocks: [
      {
        type: "paragraph",
        text: "We collect information that you directly provide to us, as well as data automatically generated by your use of our website.",
      },
      { type: "subheading", text: "Voluntary Information" },
      {
        type: "paragraph",
        text: "When you fill out our contact form, we collect your name, email address, and the content of your message.",
      },
      { type: "subheading", text: "Automated Information" },
      {
        type: "paragraph",
        text: "We use Google Analytics and similar tracking tools to collect non-identifiable technical data, including:",
      },
      {
        type: "list",
        items: [
          "IP address and general geographic location.",
          "Device type (e.g., mobile, desktop, tablet).",
          "Operating system and browser type.",
          "Website usage data (e.g., pages viewed, time spent on site, referral links).",
        ],
      },
    ],
  },
  {
    title: "2. How We Use Your Information",
    blocks: [
      {
        type: "paragraph",
        text: "We only use your information for the specific purposes for which it was collected. This includes:",
      },
      {
        type: "list",
        items: [
          "Responding to your questions, feedback, or requests submitted via the contact form.",
          "Analysing website traffic and user trends to improve our marketing, content, and website performance.",
          "Ensuring the security and proper functioning of our website.",
        ],
      },
    ],
  },
  {
    title: "3. Data Storage and Retention",
    blocks: [
      {
        type: "paragraph",
        text: "We take reasonable technical and organisational steps to protect your data from misuse, interference, loss, or unauthorised access.",
      },
      {
        type: "list",
        items: [
          "Contact Form Data: Stored securely and only retained for as long as necessary to answer your inquiry or maintain our ongoing business communication.",
          "Analytics Data: Stored by third-party providers (such as Google) on their secure servers.",
        ],
      },
    ],
  },
  {
    title: "4. Disclosure of Information Overseas",
    blocks: [
      {
        type: "paragraph",
        text: "We do not sell, rent, or trade your personal information to third parties. However, because we use global service providers like Google Analytics, the automated technical data we collect may be transferred to and stored on servers located outside of Australia (primarily in the United States).",
      },
      {
        type: "paragraph",
        text: "By using our website, you consent to this overseas data transfer.",
      },
    ],
  },
  {
    title: "5. Cookies",
    blocks: [
      {
        type: "paragraph",
        text: "Our website uses “cookies” to track user behavior and improve your browsing experience. You can choose to accept or decline cookies through your web browser settings. Disabling cookies will not prevent you from using our contact form or viewing our marketing content.",
      },
    ],
  },
  {
    title: "6. Your Rights and Access",
    blocks: [
      {
        type: "paragraph",
        text: "Under the Australian Privacy Principles, you have the right to request access to the personal information we hold about you, or to ask that we correct or delete it.",
      },
      {
        type: "paragraph",
        text: "If you wish to make a request, or if you have a complaint about how we have handled your privacy, please contact us using the details below. We will respond to your request within a reasonable timeframe (usually 30 days).",
      },
    ],
  },
];
